# -*- coding: utf-8 -*-
"""2205A21042.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIbZSjS-3L_1ykYJQDC-R8fIsv5_nxar
"""

Qualification=['venkat', 'B.Tech', 2006, 'Μ.Ε.', 2011, 'Ph.D',2018]
Experience=['SSCE', 2007, 'infosys', '2011', 'AITAM', '2013', 'SREC', '2018']
CA=Qualification + Experience #Concatination of the two Lists
print("Qualification=", Qualification)
print("Experience=", Experience)
print("CA=", CA)

Qualification=['venkat', 'B.Tech', 2006, 'Μ.Ε.', 2011, 'Ph.D', 2018]
print(Qualification)         #Print Qualification
print(Qualification[0])      #Print first item in the list
print(Qualification[1:])     #Print all items in the List except first one
print(Qualification[1:5])    #Print second to fifth items from List
print (Qualification * 2)    #Print List twice
print(Qualification[::-1])   #Print List reverse

list=['venkat', '1985']
print('venkat,birth year',list[1])
list[0]='dev'
list[1]=2017
print('dev birth year',list[1])

list=['venkat', '1985']
print(list)
del list[1]
print(list)

Grade=['A','A','B','C','A','B']
print("lowest index for grade B",Grade.index("B"))

Qualification = ['venkat', 'B.Tech', 2006, 'Μ.Ε', 2011, 'Ph.D', 2018]
print(Qualification)
print(Qualification[0])
print(Qualification[1:])
print(Qualification[1:5])
print(Qualification *2)
print(Qualification[::-1])

Name=['Ramana', 'Thanmai', 'Dev']
DOB=[1985,2014,2017]
print('Number of peoples',len(Name))
print('==================')
Details=Name+DOB
print('Biodata', Details)
print('===================')
Repetition=Name*2
print('Repetition', Repetition)
print('====================')
for x in Name:
  print(x)
print("=================")

Family=["Venkat", "Swetha"]
print('Family members', Family)
atuple=("Dev", "Thanmai")
Family.extend(atuple)
print('Family members', Family)

Name =['Ramana', 'Thanmal', 'Dev']
DOB=[1985,2014,2017]
print('Name with maximum charecters', max(Name))
print("Younger person DOB", max(DOB))
print("Name with minimum charecters", min(Name))
print('Older person DOB',min(DOB))

Family=["Ramana", "Swetha", "Thanmai", "Dev"]
print("Family members", Family)
Family.reverse()
print("Family members", Family)

Family=["Ramana","Thanmai", "Dev"]
print("Family members", Family)
Family.insert(1,"swetha")
print("Family members", Family)

Family=["Ramana", "Swetha", "Thanmai", "Dev"]
print("Family members", Family)
Family.pop()
print("Family members", Family)
Family.pop(2)
print('Family members', Family)

tuple=('venkat','B.tech',2006)
print(tuple)
print(tuple[0])
print(tuple[0:2])
print(tuple[0:])
print(tuple[::-1])
print(tuple[2:0:-1])

tiny={'Name':'venkat','Marks':891}
print(tiny)
print(tiny['Name'])
print(tiny['Marks'])
tiny['Name']='ramana'
print(tiny)

dict={}
print(dict)
dict['one']='this is one'
print(dict)
dict['2']='this is two'
print(dict)
print(dict.keys())
print(dict.values())

thisset={"apple", "banana", "cherry"}
mylist = ["kiwi", "orange"]
mylist_2=(2,3)
mylist_3={"Name": "Venkat", "School": "SRU"}

thisset.update(mylist)
thisset.update(mylist_2)
thisset.update(mylist_3)

print(thisset)

thisset={"apple", "banana", "cherry"}
for x in thisset:
    print(x)

thisset={"apple", "banana", "Cherry"}
tropical={"pineapple", "mango", "papaya"}

thisset.update(tropical)

print(thisset)

